baseURL = "https://learninganonymous.github.io/"
languageCode = "en-us"
title = "my-cybersecurity-blog"
theme = "themes/relearn"

# Optional: You can add more customization settings below

# Example for adding social media links
# [params]
#   github = "https://github.com/username"
#   twitter = "https://twitter.com/username"
